### ISSUE TITLE
大佬好 以下还有几个问题求解

### ISSUE THREAD

**Issue by addpromax** [MrXiaoM/DeathMessages#2]
1.构建失败：提示如下
/home/runner/work/DeathMessages/DeathMessages/src/main/java/dev/mrshawn/deathmessages/hooks/MythicMobs5API.java:12: error: cannot access LuminePlugin
        mythicMobs = MythicBukkit.inst();
2.请求兼容 (原作者摆烂了)
https://github.com/WeaponMechanics/MechanicsMain/releases
枪械插件 杀死玩家只会提示%weapon%就没了

**Comment by MrXiaoM** [comment]
1. 使用最新 commit
2. 理论上是个物品都可以死亡时展示，不明白你什么意思

**Comment by addpromax** [comment]
他就是用这个插件的枪械击杀之后 就会提示 xxx玩家被 %weapon% 杀死了 就没写名字

**Comment by MrXiaoM** [comment]
> 他就是用这个插件的枪械击杀之后 就会提示 xxx玩家被 %weapon% 杀死了 就没写名字

截图，说不清楚

**Comment by addpromax** [comment]
![image](https://github.com/MrXiaoM/DeathMessages/assets/124496967/9034edae-b2c1-4999-a2ca-e1dee2a2d8d9)

**Comment by addpromax** [comment]
只有这个插件的枪才会这样
可能是不兼容
![image](https://github.com/MrXiaoM/DeathMessages/assets/124496967/5bd6724c-c19d-4047-b63e-b553ea117d7c)
这是枪械名字

**Comment by MrXiaoM** [comment]
太弯弯绕绕了，我没空完整阅读枪械插件代码。刚刚提交了个忽略弹射物类型的 commit，我不确定有没有用，即使没用我也不会再跟进了

**Comment by addpromax** [comment]
好的 谢谢大佬 您更新这个插件我已经很感激了 ！ 在此感激不尽
