### ISSUE TITLE
Spigot1.19.2服务器兼容性问题

### ISSUE THREAD

**Issue by OozyMC** [MrXiaoM/DeathMessages#3]
核心：Spigot 1.19.2

_### 命令可用，玩家死亡信息无法显示_

**Comment by OozyMC** [comment]
核心：Spigot 1.19.2

### 命令可用，玩家死亡信息无法显示

`-lable:bug`

**Comment by OozyMC** [comment]
-lable:bug
核心：Spigot 1.19.2

命令可用，玩家死亡信息无法显示

**Comment by OozyMC** [comment]
核心：Spigot 1.19.2

命令可用，玩家死亡信息无法显示

**Comment by MrXiaoM** [comment]
![pic](https://github.com/MrXiaoM/DeathMessages/assets/35788433/70c4d311-8b71-4887-a465-cde4edb7dc0a)

无法复现

**Comment by OozyMC** [comment]
[](https://github.com/MrXiaoM/DeathMessages/assets/159609911/8c1ca797-7792-4c8d-82b4-ed1881713917)

上面为视频，麻烦下载查看

解决不了 :(

**Comment by MrXiaoM** [comment]
> 20240212_185859.mp4 
> 上面为视频，麻烦下载查看
> 
> 解决不了 :(

PlaceholderAPI 未安装。此时你在死亡时控制台应当有相关报错，你没有告知

**Comment by OozyMC** [comment]
谢谢大佬！！！
