### ISSUE TITLE
话说LangUtils这破玩意不支持最新版 有兴趣更新到1.21吗（）

### ISSUE THREAD

**Issue by addpromax** [MrXiaoM/DeathMessages#5]
如题

**Comment by MrXiaoM** [comment]
https://github.com/NyaaCat/LanguageUtils
PR 里有 1.20 的，可以以它为基础写 1.21 比较快

**Comment by MrXiaoM** [comment]
LangUtils 在低版本挺好用，到高版本没人更新就鸡肋了，准备学 QuickShop 那样写个自动下载指定版本语言文件

**Comment by addpromax** [comment]
确实 直接下载zh-cn.json就好了 反正里边啥都有直接调用

**Comment by addpromax** [comment]
今天心血来潮搜了个邮箱 平时一直没找到合适的 这下又找到你的插件了（）

**Comment by MrXiaoM** [comment]
新版本 spigot 有 Translatable 特性，可以获取物品的翻译键，不需要 LangUtils 了
目前还没在 1.21 测试过

**Comment by addpromax** [comment]
![image](https://github.com/user-attachments/assets/86d9e7c8-74a5-4d20-af1c-034fc2fe2b98)
Work in 1.21
